"""sample_order table

Revision ID: 98162b01877a
Revises: 3f780ee90d4a
Create Date: 2018-04-02 08:43:48.858793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98162b01877a'
down_revision = '3f780ee90d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample__order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('species', sa.String(length=255), nullable=True),
    sa.Column('tissue_types', sa.String(length=255), nullable=True),
    sa.Column('wet_samples', sa.String(length=255), nullable=True),
    sa.Column('cassettes', sa.String(length=255), nullable=True),
    sa.Column('paraffin_blocks', sa.String(length=255), nullable=True),
    sa.Column('fixative_used', sa.String(length=255), nullable=True),
    sa.Column('time_in_fixative', sa.String(length=255), nullable=True),
    sa.Column('current_storage', sa.String(length=255), nullable=True),
    sa.Column('time_in_current_storage', sa.String(length=255), nullable=True),
    sa.Column('decal', sa.Boolean(), nullable=True),
    sa.Column('orientation', sa.String(length=255), nullable=True),
    sa.Column('slides_per_sample', sa.Integer(), nullable=True),
    sa.Column('sections_per_slide', sa.Integer(), nullable=True),
    sa.Column('section_thickness', sa.Integer(), nullable=True),
    sa.Column('number_of_H_E', sa.Integer(), nullable=True),
    sa.Column('special_stain_name', sa.String(length=255), nullable=True),
    sa.Column('number_of_specials', sa.Integer(), nullable=True),
    sa.Column('region_of_interest', sa.String(length=2000), nullable=True),
    sa.Column('special_instructions', sa.String(length=2000), nullable=True),
    sa.Column('turn_around_time', sa.Integer(), nullable=True),
    sa.Column('slide_scanning', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample__order')
    # ### end Alembic commands ###
